// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsXy0x8yqvz5sU-dg6dpHQOSzwo1uvKUo',
    appId: '1:439842470609:web:c1024b65fd551ed707a3f0',
    messagingSenderId: '439842470609',
    projectId: 'bloc-6b910',
    authDomain: 'bloc-6b910.firebaseapp.com',
    storageBucket: 'bloc-6b910.appspot.com',
    measurementId: 'G-5P3JXVVXB1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAl6GNnNg06_vyZw7DYm6PpJkjBRUoU31k',
    appId: '1:439842470609:android:6592539b81dba4c607a3f0',
    messagingSenderId: '439842470609',
    projectId: 'bloc-6b910',
    storageBucket: 'bloc-6b910.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByvPxdqZMpSMafqMcEfVAhz6yCmaomssQ',
    appId: '1:439842470609:ios:bab0923dcc53ecb407a3f0',
    messagingSenderId: '439842470609',
    projectId: 'bloc-6b910',
    storageBucket: 'bloc-6b910.appspot.com',
    iosClientId: '439842470609-876idnedjfp890sjct241b73an16vtbs.apps.googleusercontent.com',
    iosBundleId: 'com.example.reddit',
  );
}
